### ISSUE TITLE
Create new instance button is doing noting

### ISSUE THREAD

**Issue by NotJohnAfterall** [Omega-dev0/Music-On-OBS#1]
Hi, I have a problem with Music on stream, I got this thing working once and then it broke. I can't create a new instance anyway, I tried to reinstall the plugin and it didn´t help either. Please help

**Comment by Omega-dev0** [comment]
Hello, which version of the plugin are you using? (You can find out by going in your browser's extension menu)

Also, could you send any errors that might pop up in the console? (Press F12 > Console and look for messages in red)

**Comment by Omega-dev0** [comment]
> The version is: Music on Stream 2.2 - Revamp
> its spamming this: WebSocket connection to 'ws://(here is ip and port)/socket.io/?EIO=4&transport=websocket' failed: Connection closed before receiving a handshake response
> 

Hi, this error means the extension cannot connect to the server.
Are you, by any chance on a public network or a network with some kind of additional security ?
