### ISSUE TITLE
Youtube Music not Working/Not getting correct reading

### ISSUE THREAD

**Issue by YDRISlive** [Omega-dev0/Music-On-OBS#2]
![Screenshot 2023-12-10 182059](https://github.com/Omega-dev0/Music-On-OBS/assets/153429010/29782ef8-585f-4d04-a695-51061c90cb18)

the extensions is working its just youtube music not giving the right thing idk how else to word this but it work on everything else except yt music. 

if you need to anything else let me know!

**Comment by Omega-dev0** [comment]
Hey, thanks for the detailed issue !

The problem was a UI change from YouTube Music, breaking some things for the extension.

The fix will be available once Google has accepted the update (usually a few hours but could take several days)

**Comment by YDRISlive** [comment]
Thank you SO MUCH!!
I was using the extension because its super easy to use and happy thats its getting fixed. I hope you have a good day!! :)

**Comment by Omega-dev0** [comment]
Fixed in commit:
63b122d55572fcdb9a4da53aab27d453ebb0d4fb

**Comment by kongyoungsik** [comment]
Hello, I am currently a YouTube Music user. It works normally on YouTube, but on YouTube Music, the music is detected, yet the overlay is not displayed. Could this be an issue on my end?

**Comment by Omega-dev0** [comment]
@kongyoungsik  Could you provide a link to the webpage you're getting the issue on? 

Could you also try disabling "detect pause" in settings > behaviour > detect pause to check if for some reason the music is not seen as paused ?
