### ISSUE TITLE
Scrolling Feature for Song Title?

### ISSUE THREAD

**Issue by mizuhehe** [Omega-dev0/Music-On-OBS#9]
Similar to the problem posted previously regarding changing the shape of the box, it'd be great to have a scrolling feature so the length of the title wouldn't matter!

**Comment by mizuhehe** [comment]
Thank you!

**Comment by Omega-dev0** [comment]
The title is now scrolling if too long on all 3 overlay styles (excluding legacy)

The state of this codebase is kind of deplorable... I hope I find the time to finish the refresh of this extension.

**Comment by mizuhehe** [comment]
I noticed the scrolling on stream! Works like a charm and now it's easier for people to find the track. Thank you again, and happy new years! Hope you had a great holiday season
